data <- read.table('household_power_consumption.txt', sep=";", na.strings="?",skip=66637, nrows=2881)
datb <- cbind(data, date=strptime(paste(data$V1, data$V2),"%d/%m/%Y %T"))
with(datb, plot(datb$date, datb$V3, "l", xlab='', ylab='Global Active Power (kilowatts)'))
dev.copy(png, file='plot2.png')
dev.off()
